### ISSUE TITLE
Breaks when having to answer questions

### ISSUE THREAD

**Issue by logix727** [madingess/EasyApplyBot#7] opened 2022-12-10 17:44 UTC
![image](https://user-images.githubusercontent.com/18837830/206868230-80d618d5-b3b9-4f25-b0d2-9ecf90aa841f.png)

and how do i default it to yes instead of no?

**Comment by madingess** [comment] 2022-12-14 21:05
Will you please provide the link to the application where this occurred? That will help me reproduce this.

It should be written to a csv file in the repository directory where the name depends on the location searched, ex: `failedRemote.csv`

**Comment by logix727** [comment] 2022-12-14 21:07
Sure can

**Comment by madingess** [comment] 2022-12-14 21:07
Though it is a new feature I am considering, there is not currently the functionality to configure a default option. 

However, it should be selecting the bottom-most option by default for dropdown, suggesting there is something else failing here.

**Comment by voidbydefault** [comment] 2022-12-29 22:41
> it should be selecting the bottom-most option by default for dropdown answers, suggesting there is something else failing here.

I can confirm that it's not defaulting to last selection in drop-down. Bot fails on jobs having additional questions. Following are instances:

```
1. Exception: Failed answering required questions or uploading required files.
Failed to apply to job! Please submit a bug report with this link: https://www.linkedin.com/jobs/view/3411094350/
```

```
2.     raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a data-control-id="g8PYgk6BKsCvhke5b92ADA==" tabindex="0" href="/jobs/view/3401765633/?eBP=JOB_SEARCH_ORGANIC&amp;recommendedFlavor=SCHOOL_RECRUIT&amp;refId=6VhQMnZXhzvIuNCUbZZdpQ%3D%3D&amp;trackingId=g8PYgk6BKsCvhke5b92ADA%3D%3D&amp;trk=flagship3_search_srp_jobs" id="ember228" class="disabled ember-view job-card-container__link job-card-list__title">...</a> is not clickable at point (287, 844). Other element would receive the click: <div data-test-artdeco-toast-item-type="success" tabindex="-1" id="ember1238" class="artdeco-toast-item artdeco-toast-item--visible ember-view">...</div>
  (Session info: chrome=108.0.5359.124)
```

Furthermore, for some reason bot is unable to write CSV file in some instances like this one:

```
  File "/home/user/Documents/EasyApplyBot/linkedineasyapply.py", line 251, in apply_to_job
    raise Exception("Failed answering required questions or uploading required files.")
Exception: Failed answering required questions or uploading required files.
Failed to apply to job! Please submit a bug report with this link: https://www.linkedin.com/jobs/view/3411094350/
Writing to the failed csv file...
Already applied to the job!
Applying to the job....
```

Hope this helps!

**Comment by madingess** [comment] 2022-12-31 19:24
I suspect this was fixed in a recent push addressing another issue. I cannot reproduce this now.

Please retry with the newest code and reopen if the issue persists.

**Closed by madingess** 2022-12-31 19:24 UTC
